# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

#   flatpak:
#     name: "Flatpak"
#     runs-on: ubuntu-latest
#     container:
#       image: bilelmoussaoui/flatpak-github-actions:gnome-40
#       options: --privileged
#     steps:
#     - uses: actions/checkout@v2
#     - uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v4
#       name: "Build"
#       with:
#         bundle: info.cemu.Cemu.flatpak
#         manifest-path: info.cemu.Cemu.json
#         cache-key: flatpak-builder-${{ github.sha }}
#     - uses: bilelmoussaoui/flatpak-github-actions/flat-manager@v3
#       name: "Deploy"
#       with:
#         repository: withertech
#         flat-manager-url: https://repo.withertech.com/flatpak/api/
#         token: "$FLAT_MANAGER_TOKEN"
#       env:
#         FLAT_MANAGER_TOKEN: ${{ secrets.FLAT_MANAGER_TOKEN }}
  # This workflow contains a single job called "build"
  flatpak:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
        image: bilelmoussaoui/flatpak-github-actions:freedesktop-21.08
#         image: freedesktopsdk/flatpak:21.08-x86_64
        options: --privileged

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Configure GPG Key
        run: |
          echo -n "$GPG_SIGNING_KEY" | base64 --decode | gpg --import
        env:
          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
      - name: Build and Upload
        run: |
          flatpak-builder --install-deps-from=flathub --force-clean --gpg-sign=597347D1434D8E68B3D72E71A892A7123B116051 --repo=repo builddir info.cemu.Cemu.json
          flat-manager-client --token "$FLAT_MANAGER_TOKEN" push --commit --publish $(flat-manager-client --token "$FLAT_MANAGER_TOKEN" create https://repo.withertech.com/flatpak/api/ main) repo/
        env:
          FLAT_MANAGER_TOKEN: ${{ secrets.FLAT_MANAGER_TOKEN }}
